### ISSUE TITLE
[FEATURE] generate from comment and cycle between suggestions

### ISSUE THREAD

**Issue by nfwyst** [codota/tabnine-nvim#115]
the plugin cant generate code from comment and i cant select suggestions, sometimes there is no completion also.
that is not so good...

**Comment by aarondill** [comment]
I don't see why it can't generate code from comments, there's just no way to specify that code should be generated from *this comment here*. In fact, I frequently write descriptions of what a file should do and have the entire file completed for me.

As to cycling/selecting completions, see #21, it's uncertain whether it will be added or not, due to complexity, but if you'd like this feature then go show your support for it and explain your use cases!

Finally, as to "sometimes there's no completion", this could be a bug or it could just be while the ai is generating new completions. I'd need more details to determine which it is, but I'd be happy to try to debug if it turns out to be a bug!
